name: Build manifest
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate manifest (flat)
        run: |
          python3 - <<'PY'
          import os, json
          def flat(root):
              out = {}
              if not os.path.isdir(root): return out
              for slug in sorted(os.listdir(root)):
                  folder = os.path.join(root, slug)
                  if not os.path.isdir(folder): continue
                  files = [
                      (os.path.join(folder, f)).replace(os.sep, '/')
                      for f in os.listdir(folder)
                      if f.lower().endswith('.ics') and os.path.isfile(os.path.join(folder, f))
                  ]
                  if files:
                      out[slug] = sorted(files)
              return out

          manifest = {
              'publics': flat('cal/publics'),
              'ues': flat('cal/ues'),
          }
          with open('manifest.json', 'w', encoding='utf-8') as fh:
              json.dump(manifest, fh, indent=2, ensure_ascii=False)
          PY

      - name: Commit manifest if changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git add manifest.json
            git commit -m "chore: update manifest.json"
            git push
          else
            echo "No changes"
          fi
